#!/usr/bin/env bash
# Build a double-clickable macOS .app bundle for someone non-technical to run.
#
# Usage:
#   ./scripts/build-mac-app.sh                  # arm64 (M-series), name "Dad's"
#   ./scripts/build-mac-app.sh --arch x64       # Intel Macs (pre-2020)
#   ./scripts/build-mac-app.sh --name "Mom's"   # library prefix shown in the header
#
# Output: dist/<Name> Library.app — right-click in Finder → Compress → send the zip.

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This builder only runs on macOS." >&2
  exit 1
fi

ARCH="arm64"
LIBRARY_NAME="Dad's"
NODE_VERSION="20.18.1"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --arch) ARCH="$2"; shift 2 ;;
    --name) LIBRARY_NAME="$2"; shift 2 ;;
    --node-version) NODE_VERSION="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,11p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

if [[ "$ARCH" != "arm64" && "$ARCH" != "x64" ]]; then
  echo "--arch must be arm64 or x64" >&2; exit 1
fi

APP_DISPLAY_NAME="${LIBRARY_NAME} Library"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIST="$ROOT/dist"
APP="$DIST/${APP_DISPLAY_NAME}.app"
NODE_CACHE="$DIST/.node-cache"

echo "==> Cleaning $DIST/${APP_DISPLAY_NAME}.app"
rm -rf "$APP"
mkdir -p "$DIST" "$NODE_CACHE"

echo "==> Building Next.js (standalone, LIBRARY_NAME=$LIBRARY_NAME)"
cd "$ROOT"
# Bake LIBRARY_NAME into the build so prerendered metadata uses the right title.
# The launcher also exports it at runtime as belt-and-suspenders.
LIBRARY_NAME="$LIBRARY_NAME" npm run build

echo "==> Assembling .app bundle"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources/app"
RES_APP="$APP/Contents/Resources/app"
cp -R .next/standalone/. "$RES_APP/"
mkdir -p "$RES_APP/.next"
cp -R .next/static "$RES_APP/.next/static"
[[ -d public ]] && cp -R public "$RES_APP/public"

echo "==> Fetching Node $NODE_VERSION ($ARCH)"
TARBALL="node-v${NODE_VERSION}-darwin-${ARCH}.tar.gz"
if [[ ! -f "$NODE_CACHE/$TARBALL" ]]; then
  curl -L --fail -o "$NODE_CACHE/$TARBALL" \
    "https://nodejs.org/dist/v${NODE_VERSION}/${TARBALL}"
fi
NODE_EXTRACTED="$NODE_CACHE/node-v${NODE_VERSION}-darwin-${ARCH}"
rm -rf "$NODE_EXTRACTED"
tar -xzf "$NODE_CACHE/$TARBALL" -C "$NODE_CACHE"
mkdir -p "$APP/Contents/Resources/node"
cp "$NODE_EXTRACTED/bin/node" "$APP/Contents/Resources/node/node"
chmod +x "$APP/Contents/Resources/node/node"

echo "==> Writing runtime config"
cat > "$APP/Contents/Resources/runtime-config.sh" <<EOF
# Generated by build-mac-app.sh. Edit at your own risk.
export LIBRARY_NAME="${LIBRARY_NAME}"
export APP_DISPLAY_NAME="${APP_DISPLAY_NAME}"
EOF

echo "==> Writing launcher"
cat > "$APP/Contents/MacOS/launcher" <<'LAUNCHER'
#!/bin/bash
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
APP_ROOT="$HERE/../Resources/app"
NODE_BIN="$HERE/../Resources/node/node"
# shellcheck disable=SC1091
source "$HERE/../Resources/runtime-config.sh"

cd "$APP_ROOT"
export NODE_ENV=production
export HOSTNAME=127.0.0.1

port_in_use() { (echo > "/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; }

# Already running? Just open the browser.
if port_in_use 3000 && curl -fs http://127.0.0.1:3000 >/dev/null 2>&1; then
  open http://127.0.0.1:3000
  exit 0
fi

PORT=""
for p in 3000 3001 3002 3003 3004; do
  if ! port_in_use "$p"; then PORT="$p"; break; fi
done
if [[ -z "$PORT" ]]; then
  /usr/bin/osascript -e "display alert \"${APP_DISPLAY_NAME} can't start\" message \"Ports 3000-3004 are all in use. Quit other apps that might be using them and try again.\""
  exit 1
fi
export PORT

# Open the browser once the server starts responding.
(
  for _ in $(seq 1 60); do
    if curl -fs "http://127.0.0.1:$PORT" >/dev/null 2>&1; then
      open "http://127.0.0.1:$PORT"
      exit 0
    fi
    sleep 0.25
  done
) &

LOG_DIR="$HOME/Library/Logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${APP_DISPLAY_NAME}.log"
exec "$NODE_BIN" server.js >>"$LOG_FILE" 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/launcher"

echo "==> Writing Info.plist"
cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>${APP_DISPLAY_NAME}</string>
  <key>CFBundleDisplayName</key><string>${APP_DISPLAY_NAME}</string>
  <key>CFBundleIdentifier</key><string>com.richmondlibrary.${LIBRARY_NAME// /-}</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>10.15</string>
</dict>
</plist>
EOF

# macOS caches bundle metadata; touch so Finder picks up changes immediately.
touch "$APP"

SIZE=$(du -sh "$APP" | cut -f1)

cat <<EOF

==> Built: $APP  ($SIZE)

To send it:
  1. In Finder, right-click "${APP_DISPLAY_NAME}.app" → Compress.
  2. Send the resulting .zip via AirDrop / Google Drive / Dropbox.

Tell the recipient:
  1. Unzip, then drag "${APP_DISPLAY_NAME}.app" into Applications.
  2. The FIRST time, right-click → Open (don't double-click). macOS will
     warn "unidentified developer" — click Open. Only needed once.
  3. After that, double-click like any other app. Books live in ~/BookShelf.
  4. To quit: right-click the dock icon → Quit.

Build options:
  --arch x64    if the target Mac is Intel (pre-2020)
  --name "X"    sets the prefix before "Library" in the header

EOF
